os: osx
osx_image: xcode12.5
language: swift
script: 
  - set -o pipefail && xcodebuild clean build test -enableCodeCoverage YES -project FCExtensionKit.xcodeproj -scheme FCExtensionKit -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.5,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode